### ISSUE TITLE
Question about how to prepare the dataset and data split

### ISSUE THREAD

**Issue by GritCS** [sheng-eatamath/PromptCAL#1]
Hi! Thanks for your remarkable work in NCD, and I'm interested in it. When I reproduce it, I'm confused about the dataset and data split.
1. what's the difference between imagenet_100, imagenet_100_gcd and imagenet_original_100?
2. What does the file tree under your /home/sheng/dataset/imagenet-img“ look like, and how are the folders arranged? 
Here are my file tree under the image datset root, but there is a bug aobut dataset when I run "methods.contrastive_training.contrastive_training_1", as the third figure shown. 
Thank you very much ! ovo
<img width="388" alt="image" src="https://user-images.githubusercontent.com/46532759/211548173-74bc794c-94a0-4b9a-b039-cff4a49305a4.png">
<img width="369" alt="image" src="https://user-images.githubusercontent.com/46532759/211548396-f7781357-fd46-42f1-952f-0f6329c4d672.png">
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/46532759/211548876-9161fa12-c41b-4677-a42e-aab3914f2d5c.png">

**Comment by sheng-eatamath** [comment]
Hello, thanks for your interest in our work. I will specify the use of ImageNet-100 dataset in readme, later. Thanks for this point.
For ImageNet-100 dataset, we simply sample 100 classes from the original ImageNet-1k dataset in another folder, and name it as 'imagenet_100_gcd' dataset. This is the dataset we use in our experiments, and the other two are deprecated. The class split we use is in https://github.com/sgvaze/generalized-category-discovery/issues/12. This folder path is actually the training folder of ImageNet-1k dataset (i.e., the subdirectories should be all synset names).

**Comment by sheng-eatamath** [comment]
And please always remember to delete `.ipynb_checkpoints` files after inspecting dataset with notebooks.
