### ISSUE TITLE
Question about the links of checkpoints

### ISSUE THREAD

**Issue by yuhodots** [sheng-eatamath/PromptCAL#2]
Hello, I read your interesting work, and thank you for opening the code!
I have a question about the Readme file.

I think there are some duplicate checkpoint links. 
For example, CIFAR-100 stage 1, stage 2, CUB stage 1, and stage 2 have the same URL links. 
Also, the links of Scars stage 1, stage 2, the Inductive version of CUB stage 1, and stage 2 are all the same.

Could you please provide proper checkpoint links?
Thank you for checking the issue :)

**Comment by sheng-eatamath** [comment]
Hi, very sorry for that. We updated the links. It should be normal now. Please have a look.
