### ISSUE TITLE
Question about the evaluation protocol

### ISSUE THREAD

**Issue by sybapp** [sheng-eatamath/PromptCAL#3]
First of all, I would like to express my gratitude for your contribution to GCD research. I have a question regarding the evaluation criteria and would appreciate your help.

In your paper, you mentioned that "We follow GCD [43] evaluation protocol in all experiments unless otherwise specified." As far as I know, GCD has two evaluation criteria (v1 and v2), and it seems that your code uses v1 instead of v2 which is used by GCD.

Could you kindly clarify which evaluation protocol should be used for your experiments?

Thank you very much for your support.

**Comment by sheng-eatamath** [comment]
Hi, thanks for your question. We would like to clarify that we adopted v2 evaluation protocal in our code (the same metrics used by GCD), except for the Inductive GNCD setup, where we adopt both. After training for two stages, the model is evaluated by the same script as GCD. We utilize the same GCD evaluation script. We will clarify it in our revised version. Thank you very much.

**Comment by sheng-eatamath** [comment]
If you have any further question, please let us know.
