### ISSUE TITLE
Questions about Kmean

### ISSUE THREAD

**Issue by devinxzhang** [sheng-eatamath/PromptCAL#5]
Thanks for your great work and codes!

I noticed that the Kmeans clustering process can be accelerated by using GPU. I am wondering if this Kmeans process could also be on multi-gpus? Otherwise, it will encounter a GPU Memory OOM issue. Currently, it uses single-gpu when using DataParallel to train the model on multi-gpus. 

Thanks!

**Comment by sheng-eatamath** [comment]
Hi, thanks for your interest to our work. We borrow the implementation of GPU-side KMeans from [GCD](https://github.com/sgvaze/generalized-category-discovery). The implementation of multi-gpu KMeans can be demanding. One simple solution can be putting KMeans computation on one additional GPU during the training. Of course, you can also re-implement KMeans for multi-gpu with torch.distributed.
If you have any further question, welcome to contact us.
