### ISSUE TITLE
Question about vit-adapted ORCA

### ISSUE THREAD

**Issue by kh12043** [sheng-eatamath/PromptCAL#7]
Hello, I read your interesting work, and thank you for opening the code!
I have some questions about the settings of the Vit-adapted ORCA used in your experiment.(mentioned in Section 4.4, table 2) 

- Did you use the dataset and dataloader from ORCA or the one from GCD?
- What were the hyperparameter settings? (Were they the same as in PromptCAL?)
- What classifier did you use? (linear classifier or DINOHead in GCD?)

Thank you for checking the issue :)

**Comment by sheng-eatamath** [comment]
Thanks for your interest on our work. First, we used the GCD dataset and both use the balancing trick. Second, the optimization params are the same. Third, we used ViT with linear layer.
