### ISSUE TITLE
Question about how to start?

### ISSUE THREAD

**Issue by jinweiisgreat** [sheng-eatamath/PromptCAL#8]
Hi, Thank you for your work! 

When I using 'bash bash_scripts/train_stage_1.sh', it didn't happen anything. 
like this:
<img width="358" alt="image" src="https://github.com/sheng-eatamath/PromptCAL/assets/69202833/5c800c87-241a-42f0-94df-edb5aa130ee4">
 What should I do? 
Should I download all datasets in my folder?

**Comment by sheng-eatamath** [comment]
Hi, thanks for your interest in our work. In `train_stage_1.sh` and `train_stage_2.sh`, the nohup command is utilized. Therefore, you can remove nohup and the last line which outputs to the file if you need to monitor the process.
