### ISSUE TITLE
Question about SemiPriori

### ISSUE THREAD

**Issue by pgh2874** [sheng-eatamath/PromptCAL#9]
Hello author!
First of all, thank you for the constructive work in Category discovery.
I have a question about the way of applying SemiPriori which adds sample-wise class labels as pairwise constraints to G˜ d.
As the dataset includes labeled and unlabeled data, unlabeled data cannot add class labels. How could SemiPriori work?

Thanks in advance.

**Comment by eatamath** [comment]
Hi, Sorry for my late reply. First of all, thanks for your interest in our work. 
After we obtain the diffused graph after affinity propagation, affinities between labeled samples are noisy. Therefore, we convert the label information of labeled data into pairwise affinities and calibrate the predicted positive/negative entries on the diffused graph. Note that this operation only affects the entries of pairs of labeled data. You can see more details in our paper and codes.

**Comment by sheng-eatamath** [comment]
Hi, Sorry for my late reply. First of all, thanks for your interest in our work.
After we obtain the diffused graph after affinity propagation, affinities between labeled samples are noisy. Therefore, we convert the label information of labeled data into pairwise affinities and calibrate the predicted positive/negative entries on the diffused graph. Note that this operation only affects the entries of pairs of labeled data. You can see more details in our paper and codes.
